- name: Install zsh, git, wget, zip, unzip
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
    - wget
    - zip
    - unzip

- name: Download antigen zsh
  get_url:
    url: https://git.io/antigen
    dest: "/home/{{ username }}/.antigen.zsh"

- name: Write .zshrc file
  template:
    src: zshrc.j2
    dest: "~{{ username }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: yes

- name: Set zsh as default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: true
